[package]
name = "frontend"
version = "0.1.0"
edition = "2021"


[[bin]]
name="linkdoku_frontend"
required-features = ["hydration"]

[dependencies]
yew = "0.20"
yew-router = "0.17.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-logger = "0.2"
log = "0.4"

[features]
hydration = ["yew/hydration"]
ssr = ["yew/ssr"]

