[workspace]
members = [
    "css",
    "database",
    "common",
    "backend",
    "frontend",
    "apiprovider",
    "frontend-core",
    "components",
    "yew-toastrack",
    "yew-bulma-tabs",
    "yew-markdown",
    "puzzleutils",
    "yew-paginator",
    "tutorials",
]
