version: "3.9"
services:
  db:
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_DB: linkdoku
      POSTGRES_USER: linkdoku
      POSTGRES_PASSWORD: linkdoku
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"

volumes:
  db-data:
