# Development system configuration for Linkdoku
# Note, nothing in this file is considered truly secret
# For example, the google client and client secret will ONLY work for `http://localhost:3000`
# so you won't be able to use it for anything interesting

port: 3000

# The Cookie secret is used to AEAD the cookies which the client is not supposed
# to be able to read/change.
cookie_secret: "01234567890123456789012345678901"

# Base URL (automatically inserted into every rendered page)
base_url: "http://localhost:3000/"

# Redirect URL for *all* OIDP setups is always the same:
redirect_url: "http://localhost:3000/-/complete-login"

# Database (when running outside of the docker)
# When inside the docker, this will be overridden by environment variables
database_url: "postgres://linkdoku:linkdoku@localhost:15432/linkdoku"

# This OpenID provider setup is only for http://localhost:3000
# You are welcome to use it when testing changes to the Linkdoku software.
# If it stops working it's because someone was abusing it enough that we
# recycled the secret etc. and you may need to set one up for yourself.
# Note, the order in which they appear here is the order they will be served
# to the linkdoku frontend.
openid:
  google:
    icon: mdi-google
    client_id: "739049102074-nbqhs8ss06d75o5lta70r01u5focufi5.apps.googleusercontent.com"
    client_secret: "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"
    # the OpenIDConnect crate automatically adds the .well-known/...
    discovery_doc: "https://accounts.google.com"
    scopes:
      - profile
      - email
  gitlab:
    icon: mdi-gitlab
    client_id: "5a5a54fb7635895ea472c5289448ecd5ef707c3552d5644dc9befa5fb437e4b8"
    client_secret: "43db4d7dbcce6eb645f76887853aaca6c66a112b2fdb50f67893737d96a74c13"
    discovery_doc: "https://gitlab.com"
    scopes:
      - profile
      - email
