[package]
name = "frontend-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = "0.8.0"
url = "2.3.1"
yew = "0.20.0"

[features]
ssr = ["yew/ssr"]
csr = ["yew/hydration"]
