[package]
name = "yew-bulma-tabs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.20"
gloo = "0.8"
stylist = { version = "0.12", features = ["yew_integration"] }
